version: 2

models:
  - name: fct_sentiment_events
    description: |
      **Fact Table: Sentiment Events**
      Grain: One row per sentiment event (Reddit post or news article)
      
      This is the core fact table for all sentiment analysis.
      Each row represents one piece of content with its sentiment score.
      
      **Join Keys:**
      - brand_key → dim_brands
      - source_key → dim_source
      
      **Used By:**
      - mart_daily_sentiment
      - mart_brand_metrics
      - Streamlit dashboard

    contract:
      enforced: true

    columns:
      - name: sentiment_event_id
        description: Unique surrogate key for this event
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: brand_key
        description: Foreign key to brand dimension
        data_type: varchar
        tests:
          - not_null

      - name: sentiment_score
        description: Sentiment score from -1 (very negative) to 1 (very positive)
        data_type: double
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -1
              max_value: 1

      - name: published_date
        description: Date the content was published
        data_type: date
        tests:
          - not_null

      - name: quality_flag
        description: Data quality assessment
        data_type: varchar
        tests:
          - accepted_values:
              values: ['VALID', 'INVALID_SENTIMENT', 'NULL_HEADLINE']

      - name: _dbt_run_timestamp
        data_type: varchar
        description: Internal dbt run timestamp

      - name: _dbt_updated_at
        data_type: timestamp with time zone
        description: Internal dbt update timestamp

      - name: body_text
        data_type: varchar
        description: Full text of the Reddit post or news article

      - name: brand
        data_type: varchar
        description: Brand mentioned in the content

      - name: content_id
        data_type: varchar
        description: Source-specific content ID

      - name: creator
        data_type: varchar
        description: Username or author

      - name: engagement_count
        data_type: bigint
        description: Number of upvotes, likes, or shares

      - name: headline
        data_type: varchar
        description: Headline text (if applicable)

      - name: ingested_at
        data_type: timestamp
        description: Time when the data was ingested

      - name: published_at
        data_type: timestamp with time zone
        description: Original publish timestamp

      - name: published_day_of_week
        data_type: bigint
        description: Day of the week (0=Monday)

      - name: published_hour
        data_type: bigint
        description: Hour of publication

      - name: published_month
        data_type: bigint
        description: Month of publication

      - name: published_year
        data_type: bigint
        description: Year of publication

      - name: sentiment_category
        data_type: varchar
        description: Text category of sentiment (Positive/Negative/Neutral)

      - name: source
        data_type: varchar
        description: Source platform (e.g., Reddit, NewsAPI)

      - name: source_key
        data_type: integer
        description: Foreign key to source dimension

      - name: parent_company        
        description: Parent company owning the brand
        data_type: varchar
        
      - name: brand_category       
        description: Product category (e.g., Beverages, Personal Care)
        data_type: varchar
        
      - name: subreddit         
        description: Reddit subreddit where post was found (null for news)
        data_type: varchar

  - name: mart_daily_sentiment
    description: |
      **Mart: Daily Sentiment Aggregates**
      Grain: One row per (date, brand)
      Materialization: Incremental merge
      
      Daily aggregates of sentiment metrics by brand.
      Used for dashboard and trend analysis.

    contract:
      enforced: true

    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ["sentiment_date", "brand"]

    columns:
      - name: sentiment_date
        description: Date of aggregation
        data_type: date
        tests:
          - not_null

      - name: brand
        description: Brand name
        data_type: varchar

      - name: avg_sentiment
        description: Average sentiment for the day
        data_type: double
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -1
              max_value: 1

      - name: min_sentiment
        description: Minimum sentiment score
        data_type: double

      - name: max_sentiment
        description: Maximum sentiment score
        data_type: double

      - name: stddev_sentiment
        description: Standard deviation of sentiment
        data_type: double

      - name: content_count
        description: Number of content pieces
        data_type: bigint

      - name: positive_count
        description: Count of positive sentiment
        data_type: bigint

      - name: negative_count
        description: Count of negative sentiment
        data_type: bigint

      - name: neutral_count
        description: Count of neutral sentiment
        data_type: bigint

      - name: positive_ratio
        description: Ratio of positive content
        data_type: double

      - name: total_engagement
        description: Total engagement count
        data_type: hugeint

      - name: avg_engagement
        description: Average engagement
        data_type: double

      - name: source_count
        description: Number of unique sources
        data_type: bigint

      - name: z_score_sentiment
        description: Z-score for anomaly detection
        data_type: double

      - name: anomaly_flag
        description: Whether this day's sentiment is statistically anomalous
        data_type: varchar
        tests:
          - accepted_values:
              values: ['NORMAL', 'ANOMALY']

      - name: mart_load_date
        description: Date the mart was loaded
        data_type: timestamp with time zone

  - name: dim_brands
    description: Brand dimension table with metadata
    columns:
      - name: brand_key
        description: Surrogate key for brand
        tests:
          - unique
          - not_null
      - name: brand
        description: Brand name
      - name: category
        description: Product category
      - name: parent_company
        description: Parent company name

  - name: dim_sources
    description: Source dimension for data origins
    columns:
      - name: source_key
        description: Surrogate key for source
        tests:
          - unique
          - not_null
      - name: source_name
        description: Source platform name

  - name: mart_brand_competitive_analysis
    description: |
      **Mart: Brand Competitive Analysis**
      Grain: One row per brand
      
      Competitive intelligence including share of voice, sentiment benchmarks,
      engagement metrics, and competitive positioning.
      
      **Key Metrics:**
      - Share of Voice: % of total mentions
      - Net Sentiment Score: (Positive % - Negative %)
      - Competitive Position: MARKET_LEADER, NICHE_FAVORITE, AT_RISK, etc.
      
      **Used By:**
      - Competitive dashboard
      - Executive reports
      - Brand strategy analysis

    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ["brand", "parent_company"]

    columns:
      - name: brand
        description: Consumer brand name
        data_type: varchar
        tests:
          - not_null

      - name: parent_company
        description: Parent company owning the brand
        data_type: varchar
        tests:
          - not_null

      - name: brand_category
        description: Product category
        data_type: varchar

      - name: total_mentions
        description: Total mentions across all sources
        data_type: bigint
        tests:
          - not_null

      - name: share_of_voice_pct
        description: Share of voice as percentage of total mentions
        data_type: double
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100

      - name: avg_sentiment
        description: Average sentiment score for the brand
        data_type: double
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -1
              max_value: 1

      - name: net_sentiment_score
        description: Positive % minus Negative %
        data_type: double

      - name: competitive_position
        description: Competitive positioning classification
        data_type: varchar
        tests:
          - accepted_values:
              values: ['MARKET_LEADER', 'NICHE_FAVORITE', 'AT_RISK', 'LOW_VISIBILITY', 'MIDDLE_PACK']

      - name: sentiment_vs_category
        description: Performance vs category average
        data_type: varchar
        tests:
          - accepted_values:
              values: ['OUTPERFORMING', 'UNDERPERFORMING', 'AT_PAR']

      - name: sentiment_rank_in_category
        description: Sentiment rank within product category
        data_type: bigint

      - name: volume_rank_in_category
        description: Volume rank within product category
        data_type: bigint

      - name: engagement_rate
        description: Average engagement per Reddit mention
        data_type: double

      - name: momentum_pct
        description: 7d vs 30d growth momentum percentage
        data_type: double

      - name: reddit_mentions
        description: Count of Reddit mentions
        data_type: bigint

      - name: news_mentions
        description: Count of news mentions
        data_type: bigint

      - name: positive_mentions
        description: Count of positive sentiment mentions
        data_type: bigint

      - name: negative_mentions
        description: Count of negative sentiment mentions
        data_type: bigint

      - name: neutral_mentions
        description: Count of neutral sentiment mentions
        data_type: bigint

      - name: _created_at
        description: Timestamp when record was created
        data_type: timestamp with time zone

      - name: _dbt_run_timestamp
        description: dbt run timestamp
        data_type: varchar


  - name: mart_trending_topics
    description: |
      **Mart: Trending Topics**
      Grain: One row per (brand, topic) combination
      
      Identifies trending discussion topics and themes by brand.
      Uses keyword extraction and trending score calculation.
      
      **Topics Tracked:**
      - Product Launch
      - Pricing
      - Quality Issues
      - Sustainability
      - Health & Nutrition
      - Marketing & Advertising
      - Brand Comparison
      - Taste & Flavor
      
      **Trending Score:**
      Combines recency, volume growth, and engagement
      
      **Used By:**
      - Topic analysis dashboard
      - Brand monitoring alerts
      - Content strategy planning

    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list: ["brand", "topic"]

    columns:
      - name: brand
        description: Consumer brand name
        data_type: varchar
        tests:
          - not_null

      - name: parent_company
        description: Parent company owning the brand
        data_type: varchar

      - name: topic
        description: Discussion topic/theme
        data_type: varchar
        tests:
          - not_null
          - accepted_values:
              values: 
                - 'Product Launch'
                - 'Pricing'
                - 'Quality Issues'
                - 'Sustainability'
                - 'Health & Nutrition'
                - 'Marketing & Advertising'
                - 'Brand Comparison'
                - 'Taste & Flavor'

      - name: mention_count
        description: Total mentions of this topic for the brand
        data_type: bigint
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 3  # Filtered in model

      - name: trending_score
        description: Calculated trending score (recency + growth + engagement)
        data_type: double
        tests:
          - not_null

      - name: trend_status
        description: Trending classification
        data_type: varchar
        tests:
          - accepted_values:
              values: ['HOT', 'TRENDING', 'STABLE', 'EMERGING']

      - name: sentiment_tone
        description: Overall sentiment about this topic
        data_type: varchar
        tests:
          - accepted_values:
              values: ['POSITIVE_BUZZ', 'NEGATIVE_BUZZ', 'NEUTRAL_DISCUSSION']

      - name: avg_sentiment
        description: Average sentiment score for topic mentions
        data_type: double
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -1
              max_value: 1

      - name: positive_mentions
        description: Count of positive mentions
        data_type: bigint

      - name: negative_mentions
        description: Count of negative mentions
        data_type: bigint

      - name: positive_pct
        description: Percentage of positive mentions
        data_type: double

      - name: reddit_mentions
        description: Reddit mentions for this topic
        data_type: bigint

      - name: news_mentions
        description: News mentions for this topic
        data_type: bigint

      - name: mentions_last_7d
        description: Mentions in last 7 days
        data_type: bigint

      - name: mentions_last_14d
        description: Mentions in last 14 days
        data_type: bigint

      - name: avg_engagement
        description: Average engagement (Reddit only)
        data_type: bigint

      - name: max_engagement
        description: Maximum engagement seen
        data_type: bigint

      - name: latest_mention
        description: Timestamp of most recent mention
        data_type: timestamp

      - name: topic_rank_for_brand
        description: Rank of this topic within the brand
        data_type: bigint

      - name: topic_total_mentions
        description: Total mentions of this topic across all brands
        data_type: bigint

      - name: _created_at
        description: Timestamp when record was created
        data_type: timestamp with time zone

      - name: _dbt_run_timestamp
        description: dbt run timestamp
        data_type: varchar