name: 'lab2_market_sentiment'
version: '1.0.0'
config-version: 2
profile: 'lab2_market_sentiment'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']

target-path: 'target'
clean-targets: ['target', 'dbt_modules', 'dbt_packages']

vars:
  sentiment_threshold_positive: 0.5
  sentiment_threshold_negative: -0.5
  lookback_days: 90

models:
  lab2_market_sentiment:
    staging:
      +materialized: ephemeral
      +tags: ['staging', 'daily']
    
    intermediate:
      +materialized: table
      +tags: ['intermediate', 'daily']
      +on_schema_change: fail

    dimensions:                                
      +materialized: table
      +tags: ['dimension']
      +on_schema_change: append_new_columns
    
    mart:
      +materialized: table
      +tags: ['mart', 'daily']
      
      fct_sentiment_events:
        +materialized: incremental
        +incremental_strategy: 'delete+insert'  
        +unique_key: 'sentiment_event_id'       
        +on_schema_change: 'append_new_columns' 
        +unique_id: 'sentiment_event_id'
        +on_schema_change: fail
        +contract:
          enforced: false
      
      mart_daily_sentiment:
        +materialized: incremental
        +incremental_strategy: 'delete+insert'  
        +unique_key: ['sentiment_date', 'brand']  
        +on_schema_change: fail

      mart_brand_competitive_analysis:
        +materialized: table
        +tags: ['mart', 'competitive', 'analytics']
        +on_schema_change: append_new_columns

      mart_trending_topics:
        +materialized: table
        +tags: ['mart', 'topics', 'analytics']
        +on_schema_change: append_new_columns

    

tests:
  lab2_market_sentiment:
    +store_failures: true
    +schema: dbt_test__audit
